### ISSUE TITLE
how contribute to this repository?

### ISSUE THREAD

**Issue by solarsbeans** [ctwhome/notidian#2]
Hi, I want to be maintainer of this repository, I would like to contribute to this repository and gain experience in developing open source software. How can I do this today?

Well, I was thinking about trying to add more features:
- Can this code run on Netlify, Repl-it or Render as well too? I think about adding separate instances for interoperability. The user could choose where the GUI is generated: Vercel, Netlify, Render or Replit. This initial resource would be very important.
-  Another feature that I find interesting is the choice of fonts. Is it possible to change notidian fonts: Arial, tahoma etc?

*What do you think of these 2 features to notidian?*

**Comment by ctwhome** [comment]
Hi @solarsbeans ,feel free to add any PR with the features you think can be useful. As a simple note, this repository is very experimental until I find the perfect match for the best note taking application experience.

**Comment by solarsbeans** [comment]
Hi @ctwhome, thanks you for all information here, now.
